this is the main page
future-proof-tn/randev-guide pull request #1
Opened 2023-03-13 13:37 UTC by yregaieg

2023-03-13 13:40 UTC, yregaieg commented
@Doniafrikha Please take into consideration the following notes:

- [ ] All file names should be significant and self-explaining.
- [ ] All image files should only care about one single screen, if you want to put multiple screens net to one an other we can later use formatting. This guide is meant to be usable both on Desktop web and mobile web, having such large / complex images makes it super hard to visualize the guide from a mobile terminal.
- [ ] Each and every step should be accompanied notonly with a screenshot, but also with some explanation in text.

2023-03-13 13:48 UTC, yregaieg commented on docs/getting-started.fr.md
> +  ![Cree un compte](./about/assets/cree un compte (2).png){ width="700" }
You may change the photo attributes (such as width ... etc ) more details on available attributes here: https://jimandreas.github.io/mkdocs-material/reference/images/#usage

2023-03-13 13:48 UTC, yregaieg commented on docs/getting-started.fr.md
> +  <figcaption></figcaption>
caption missing

2023-03-13 13:48 UTC, yregaieg commented on docs/getting-started.fr.md
> +  ![Cree un compte](./about/assets/cree un compte (2).png){ width="700" }
Why use ./about/assets/ instead of creating an assets folder at this level ?

2023-03-13 13:48 UTC, yregaieg commented on docs/getting-started.fr.md
> +  ![Cree un compte](./about/assets/11.png){ width="700" }
asset name + asset location

2023-03-13 13:48 UTC, yregaieg commented on docs/getting-started.fr.md
> +  <figcaption></figcaption>
Caption ?

2023-03-13 16:13 UTC, safa-rekik commented on docs/getting-started.fr.md
>  ### Moyennant d'un email et mot de passe
I think that the correct french expression is "Moyennant un email et un mot de passe"

2023-03-13 17:10 UTC, safa-rekik requested changes
Hi, I hesitated whether to submit a comment or request changes. but I think that the user guide should include the nominal scenarios of FB and google login.  We'll check this tomorrow with PO.

2023-03-13 17:10 UTC, safa-rekik commented on docs/index.fr.md
> +Adresse: Cite el ons techno pole , 3021 Sfax.
technopole

2023-03-13 17:10 UTC, safa-rekik commented on docs/getting-started.fr.md
> +4-Entrer vos informations personelles.
personnelles

2023-03-13 17:10 UTC, safa-rekik commented on docs/getting-started.fr.md
> +5-Cliquer sur creer un compte.
créer et non pas creer :D (attention au accents)

2023-03-15 14:40 UTC, regaieg1 commented on docs/index.fr.md
> +Email: mr@futureproof.tn
Please change this email to: contact@randev.io

2023-03-23 10:52 UTC, safa-rekik commented on docs/getting-started.fr.md
> +Vous pouvez vous connecter a travers de votre compte google en indiquant votre adresse e-mail ou votre
@Doniafrikha  I checked this with Mohammad Regaieg, Please remove the pictures that show the detail of the login with google. It is not necessarily to do so.

2023-08-22 12:42 UTC, yregaieg commented
@safa-rekik You can close this if you can confirm that everything from Contact / release notes and getting started has already been included into main branch or is obsolete

2023-08-22 15:01 UTC, safa-rekik commented
@yregaieg We have already a ticket that dedicated for "the getting started" page, can I close the PR just after opening tickets to create appropriate content for  "release note" and "contact" pages ?

2023-08-22 15:21 UTC, yregaieg commented
OkSent from my iPhoneOn 22 Aug 2023, at 17:01, safa-rekik ***@***.***> wrote:﻿
@yregaieg We have already a ticket that dedicated for "the getting started" page, can I close the PR just after opening tickets to create appropriate content for  "release note" and "contact" pages ?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-08-31 06:14 UTC, closed without merging