RNDV-1620 added the videos to the guide
future-proof-tn/randev-guide pull request #10
Opened 2023-08-25 07:24 UTC by DaliNeji

2023-08-28 10:37 UTC, safa-rekik requested changes
Concerning the full experience video, Mohammad asked me to put it in the  "quick start" page.

2023-08-28 10:37 UTC, safa-rekik commented on docs/user-guide/index.fr.md
>  ## Vérification des attributs de la boutique
Please change this title "Consulter les détails de la boutique"

2023-08-28 10:37 UTC, safa-rekik commented on docs/user-guide/index.fr.md
> +<source src="./Videos/FR/Final-product/GoogleLogin.mp4" type="video/mp4">
make sure to put the google login video under the google login title, and login with email cideo aunder login with email video

2023-08-29 09:02 UTC, safa-rekik approved these changes

2023-08-29 09:06 UTC, safa-rekik commented
@yregaieg Hi, I couldn't merge this ticket, I think because you requested a change, please approve and merge

2023-08-31 06:14 UTC, yregaieg approved these changes
Still not really happy with the way this is implemented, but I am approving to not stall the merge

2023-08-31 06:14 UTC, merged