feature/RNDV-1327 User guide website (Instant booking feature)
future-proof-tn/randev-guide pull request #2
Opened 2023-03-22 15:13 UTC by Doniafrikha

2023-03-28 13:28 UTC, safa-rekik commented on docs/store-owner-guide/index.fr.md
> + Prix : Mettez le prix que vous souhaiter pour fournir ce service , vous pouvez vous inspirer des autres boutiques similaire pour déterminer un prix justifié.
Ici ce n'est pas du tout le contexte pour proposer au propriétaire du magasin comment il peut s'inspirer pour donner un prix, l'essentielle c'est qu'il comprenne qu'il doit mettre un prix pour le service

2023-03-28 13:34 UTC, safa-rekik commented on docs/store-owner-guide/index.fr.md
> +Reservation limitee : Generalement pour des raisons de pratiques , la reservation doit etre limitee en un nombre bien precis ( reservation directe desactive ) dont un client peut reserver en une seul
la notion de reservation limitée n'est pas claire du tout, il faut la réexpliquer

2023-03-28 13:35 UTC, safa-rekik commented on docs/store-owner-guide/index.fr.md
> +Service designee :  Déterminent ce que chaque membre peut faire , Vous pouvez attribuer des permissions spécifiques à chaque employee , en utilisant cette option , vous pouvez désigner un service à u
nn il ne s'agit pas d'une persmission

2023-04-12 10:09 UTC, safa-rekik requested changes
@Doniafrikha J'ai essayer de mettre les commentaire nécessaires.
D'une façon générale : 
-Essai de trouver un correcteur orthographique pour VS code pour réduire le nombre des faute d'orthographe et de grammaire.
-Attentions au espaces et au virgule! il faut écrire 'Aujourd'hui, j'ai mangé un gâteau' et non pas ' Aujourd'hui , j'ai mangé un gâteau' ;) 
Je n'est pas terminer le "review' du reste de la partie du propriétaire(contrainte de temps l'exiges) mais je propose que tu vienne une autre fois au bureau pour que l'on puisse travailler ensemble et le finir une fois pour toute;) à partir demain après midi je serai disponible inchallah

2023-07-07 08:36 UTC, safa-rekik commented on docs/store-owner-guide/index.fr.md
> +### Paramétrage des ressources et des catégories de ressources
@DaliNeji here is the pull request

2023-08-21 10:07 UTC, safa-rekik commented
@yregaieg shall we close this PR

2023-08-22 12:44 UTC, yregaieg commented
@safa-rekik same note here, if all changes have been accounted for, or rendered obsolete, this can then be closed!

2023-08-31 06:15 UTC, closed without merging