staff user guide
future-proof-tn/randev-guide pull request #7
Opened 2023-07-13 16:06 UTC by DaliNeji

2023-07-14 10:39 UTC, safa-rekik requested changes
please check ly comments there.

2023-07-14 10:39 UTC, safa-rekik commented on docs/staff-guide/index.md
> +To do so you need to open the Randev application
Add the bullet list

2023-07-14 10:39 UTC, safa-rekik commented on docs/staff-guide/index.md
> +it will redirect you to a page where you should provide the phone number of the client, an optional name field, which service does he want and there is a de-activated button that when clicked brings
Elaborate this in the same way I did in the french section, and do not forget using the bullet lists of markdown

2023-07-14 10:39 UTC, safa-rekik commented on docs/staff-guide/index.md
> +You can always share your store with your clients via link or via QR code so what are you waiting for?
As usual, waiting for some user guide to explain this xD

2023-07-14 10:39 UTC, safa-rekik commented on docs/staff-guide/index.fr.md
> +Vous pouvez acceder a votre calendrier et voir toutes vos reservations .
plus de details STP ! il faut surtout souligner qu'il faut cliquer sur le boooking gris pour ouvrir les details du booking (fait de même pour l'anglaais)

2023-07-17 15:08 UTC, safa-rekik requested changes
@DaliNeji A part from the detailed comments dow there, these are the overall remarks:

- Arabic section, You need to investigate a solution for the ugly display of the bullet lists. And concerning the content, check it again with Mohammad Regaieg.
- For the french and english section : 
  Make sure to install a grammar/spelling check in your editor, pay attention to details such as capital letters and slight mistake (Most of them are made by me I admit 😅 )

2023-07-18 11:04 UTC, safa-rekik reviewed
@DaliNeji Almost done, just correct some spelling (I highly recommend you configure your ide so that it does this for you!)
and please, change the instant booking screen shots so that the book button is shown (I should have made this remark in the last review, sorry)

2023-07-18 11:04 UTC, safa-rekik commented on docs/staff-guide/index.fr.md
> +Vous pouvez changer l'affichage des rendez-vous en cliquant sur le boutton a droite en haut de la page.
bouton xD

2023-07-18 11:04 UTC, safa-rekik commented on docs/staff-guide/index.fr.md
> +- Ouvrez l'application Randev
Ay ay ay, c'est l'infinitif qu'il faut utiliser après vous devez !!!!

2023-07-18 12:11 UTC, DaliNeji commented on docs/staff-guide/index.fr.md
> +- Ouvrez l'application Randev
> Ay ay ay, c'est l'infinitif qu'il faut utiliser après vous devez !!!!

It was like that but then I changed it I don't know why I did that

2023-07-24 14:29 UTC, safa-rekik approved these changes
This user guide is acceptable

2023-07-24 14:29 UTC, merged